sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t gilir/rpi-alpine:build .
# test image
- docker run gilir/rpi-alpine:build uname -a
# push image
- >
  TAG=$(grep "FROM " Dockerfile | sed 's/.*://')
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    docker tag gilir/rpi-alpine:build gilir/rpi-alpine:$TAG
    docker tag gilir/rpi-alpine:build gilir/rpi-alpine:latest
    docker push gilir/rpi-alpine:$TAG
    docker push gilir/rpi-alpine:latest
  else
    if [ "$TRAVIS_BRANCH" == "$TAG" ]; then
    docker tag gilir/rpi-alpine:build gilir/rpi-alpine:$TAG
    docker push gilir/rpi-alpine:$TAG
  fi
